### ISSUE TITLE
Melhorias no Editor de Portfólio

### ISSUE THREAD

**Issue by diogosp** [brasadesign/artunlimited#10]
Adicionar campos de edição para cada Galeria no editor de posts do Portfólio:

- Galeria de Imagens
- Galeria de Clippings
- Galeria de Materiais
- Galeria de Vídeos

**Comment by matheusgimenez** [comment]
Eu mudei algumas coisas, mas acho que precisa mudar algo mais, pode me dar um feedback @diegorojas ?

http://beta.brasa.art.br/artunlimited/portfolio/agua/

**Comment by diegorojas** [comment]
Aqui, temos duas questões da ordem das coisas que tinhamos fechado. Mas que eu devia ter documentado aqui, vamos lá, no backend devemos ter a seguinte ordem:
- Titulo
- Informações do Projeto
- Content
- Configurações de Portfolio
- Área de Audiovisual

ai o outro detalhe, é que aconteceu alguma coisa com as abas do q translate, elas se duplucaram no titulo do CPT:

![errro-q-translate](https://user-images.githubusercontent.com/3632627/28441320-8f553546-6d80-11e7-96e1-1ae02b9853d7.png)

**Comment by diegorojas** [comment]
Acabei de ver que a aba de linguas se repete em outros lugares tb, embaixo do content e te outra entre a area de imagens e a area de audiovisual

**Comment by diogosp** [comment]
@diegorojas esta ordem que você colocou aí, é possível a gente arrastar os campos e cada usuário ter uma visualização não? Ou dá pra fixar isso? Pq realmente está trocada a ordem dos campos como você colocou.

**Comment by diogosp** [comment]
@diegorojas @matheusgimenez a questão do CLIPPING/Galeria de Imagens via Jetpack é isso? resolveu esta parte tb?

**Comment by diegorojas** [comment]
Sim, Matt resolveu isso ai, tirando o plugin e usando jetpack para Material Grafico e o template de attachament (image.php) para o clipping

**Comment by matheusgimenez** [comment]
Feito

**Comment by diegorojas** [comment]
Acho importante o audiovisual aparecer antes do material gráfico, tanto na visualização do site pelo visitante, quanto no painel de controle do site. E, claro, nos botão de navegação lateral. Ordem final seria "Fotos", "Sobre", "Audiovisual", "Material gráfico" e "Clipping"

**Comment by diegorojas** [comment]
Na página de cada projeto precisa estar escrito "Material gráfico" e não só "Gráfico" como vocês mandaram no exemplo abaixo:

**Comment by diegorojas** [comment]
Na parte de Material Gráfico também precisa haver um campo para preenchimento de texto entre o Título "Material gráfico" e a galeria de fotos.

**Comment by matheusgimenez** [comment]
Ta feito

**Comment by diegorojas** [comment]
Cara, tá tudo certinho do ponto de vista de funcionalidade, mas tem o detalhe. No menu de navegação precisa ficar só "gráfico" and "graphic" mesmo... É só no corpo do Portfolio que precisa ser trocado para "Material Gráfico" e "Graphic Design", ok?

**Comment by diegorojas** [comment]
Boa mano!! Fechou!!!
