### ISSUE TITLE
Adicionar Galeria de Áudio-Video

### ISSUE THREAD

**Issue by diogosp** [brasadesign/artunlimited#11]
Adicionar no Portfólio a seção Galeria de Áudio-Vídeo.

**Comment by diegorojas** [comment]
Acho que isso já tá contemplado na issue #10. Quer tratar de forma diferenciada mesmo? Acho que então aqui coloca aqui Audiovisual e tira "Galeria de Videos" da issue #10

**Comment by diogosp** [comment]
Ahhh não. fique sussa. Era só pra controlar melhor as entregas. Se isto já está em outra Issue é melhor deixar lá

**Comment by diegorojas** [comment]
Beleza! Mas deixa ver mesmo com o matheus o que vamos fazer de fato. Ai qq coisa fecho essa aqui memo

**Comment by matheusgimenez** [comment]
Feito

**Comment by matheusgimenez** [comment]
http://beta.brasa.art.br/artunlimited/portfolio/agua/

**Comment by diegorojas** [comment]
Funcionalmente tá lindo. Só ficou estranho no editor internamente, ta bem feio:

![au-portfolio-video-back](https://user-images.githubusercontent.com/3632627/28441063-4797f2d0-6d7f-11e7-9175-80edbdbcd623.png)

Num da para tirar o texto "Preencha com o URL do vídeo no YouTube, Vimeo, etc." e colocar acima. para não ter essa margem esquerda grande ai?

**Comment by diogosp** [comment]
@matheusgimenez eu to com o @diegorojas.
A usabilidade do editor tá prejudicada.

Eu faria as seguintes alterações:
- Altera o texto "preencha com..." conforme o @diegorojas colocou.
- o Botão ADICIONAR LINHA troca para ADICIONAR VÍDEO (print).
- Se desse pra colocar o ADICIONAR na parte de CIMA dos vídeos já inseridos seria melhor, pq fica escondido lá embaixo

<img width="956" alt="editar_portfolio_ _art_unlimited_ _wordpress" src="https://user-images.githubusercontent.com/5107285/28471786-a4d452aa-6e14-11e7-8dc2-9dbb898afa29.png">

**Comment by diegorojas** [comment]
Concordo com o Diogo, mas acho que o Remover só ta certo. Acho que o Diogo não entendeu como funciona, isso significa que a usabilidade num ta doida, mas num sei o que sugerir para melhorar...

**Comment by diogosp** [comment]
@matheusgimenez esta é uma pendência que vc precisa resolver.
Falta isso pra podermos entregar.

**Comment by matheusgimenez** [comment]
Feito

**Comment by diogosp** [comment]
@matheusgimenez ainda faltou um detalhe: colocar o botão INSERIR LINHA na parte de cima do editor de videos. pra que ele nao fique perdido lá embaixo. E trocar o Linha por VIDEO no botão

**Comment by matheusgimenez** [comment]
@diogosp Eu acredito que nao consigo fazer a questao de mudar a posiçao do botao, a parte de trocar o titulo dele acho que sim.

**Comment by diogosp** [comment]
@matheusgimenez tudo bem @deshawn manda BRASA

**Comment by diegorojas** [comment]
Tenta mudar o texto sim man, fará uma baita diferença na usabilidade.. Tirar a margem direita, ja ajudou muito

**Comment by matheusgimenez** [comment]
Consegui fazer as duas coisas no final.

Subi no beta, testem lá

**Comment by diegorojas** [comment]
Oi @diogosp, to com o matheus aqui em casa. Fechamos que o botão de adicionar video tem que ficar abaixo do videos mesmo. Para ir na ordem que vai ficar no front end. Testei aqui e tá beleza, vou fechar a issue.

**Comment by diegorojas** [comment]
Acho importante o audiovisual aparecer antes do material gráfico, tanto na visualização do site pelo visitante, quanto no painel de controle do site. E, claro, nos botão de navegação lateral. Ordem final seria "Fotos", "Sobre", "Audiovisual", "Material gráfico" e "Clipping"
