### ISSUE TITLE
Possibilitar que uma single-portfolio.php filha seja diferente da single-portfolio.php mae

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/artunlimited#4]
Entao, eu estou criando paginas filhas de todos os Portifolios para abrigarem mais informacoes de cada projeto, por hora teste aqui:

http://beta.brasa.art.br/artunlimited/portfolio/abraham-palatnik-a-reinvencao-da-luz/

Ao clicar em Clipping ou Comunicacao Visual voce e redirecionado para uma pagina filha que tem o slider, isso nao deveria acontecer, preciso de uma single-portfolio.php filha SEM o slider. 

http://beta.brasa.art.br/artunlimited/portfolio/abraham-palatnik-a-reinvencao-da-luz/clipping/

Achei o seguinte caminho, mas nao consegui modificar: 
// testando funcao para diferenciar single-cpt pai de single-cpt filhas
// http://css-tricks.com/snippets/wordpress/if-page-is-parent-or-child/

function is_tree($pid) {      // $pid = The ID of the page we're looking for pages underneath
	global $post;         // load details about this page
	if(is_page()&&($post->post_parent==$pid||is_page($pid))) 
               return true;   // we're at the page or at a sub page
	else 
               return false;  // we're elsewhere
};

**Comment by matheusgimenez** [comment]
Essa função do css tricks não é necessária.. é só fazer um if antes de trazer o HTML do slider e nem precisa verificar se o CPT, já que o if estaria dentro do arquivo single-portfolio.php

Aguarda um pouco.. to ligando o note e já fecho esse

**Comment by matheusgimenez** [comment]
Pronto! :)
