### ISSUE TITLE
Tornar os querys de categorias navegaveis com AJAX na archive-portfolio.php

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/artunlimited#5]
Por favor usar sempre branch beta para desenvolvimento

Precisamos implementar na página abaixo:
http://beta.brasa.art.br/artunlimited/portfolio/

![portfolio-art](https://cloud.githubusercontent.com/assets/3632627/6274900/e8d74450-b861-11e4-8834-c04e04271598.png)

O mesmo tipo de navegação entre categorias que esse exemplo aqui:
http://demo.natko.com/handbook/

Tranquilo?

**Comment by diegorojas** [comment]
Como falamos no telegram, é importante criar um botão "Todos" ou "Todas" para desfazer a filtragem depois de clicada...

Podemos também ressaltar o css da categoria escolhida e só colocar um "X" no final da lista, o que acha?

**Comment by matheusgimenez** [comment]
Pode ser

**Comment by diegorojas** [comment]
Isto esta feito. A unica coisa que nao consegui finalizar foi colocar um array 'public' => true, no query que aparece quando clico em ver todas. Coloca isso la por favor que eu fecho a issue :)

**Comment by diegorojas** [comment]
Ta dando para visualizar aqui:
http://beta.brasa.art.br/artunlimited/portfolio/

Uma ultima coisa, perceba que o comando não esta funcionando no primeiro clique, só no segundo.

**Comment by matheusgimenez** [comment]
Aqui ta funcionando no primeiro click '-'

E o esquema de public não entendi

**Comment by diegorojas** [comment]
Beleza, vou testar mais o primeiro clique @everaldomatias testa isso também por favor e só diz se para vc ta no primeiro ou na segunda linkada de uma categoria?

O esquema do public é só para tirar do query "ver todas" os posts que estiverem em rascunho. Veja lá, ao entrar na archive-projetos "oscar niemeyer" não aparece, depois de filtrar e clicar em ver todas eles aparece, ele está em rascunho no dashboar.

**Comment by diegorojas** [comment]
Matheus, para mim ainda esta na segunda linkada ainda, a outra coisa ta certo.

Mas vou fechar a issue, depois vemos isso.
