### ISSUE TITLE
Menu e Sidebar Fixos na rolagem

### ISSUE THREAD

**Issue by diogosp** [brasadesign/artunlimited#8]
Fixar sidebar e menu.

**Comment by matheusgimenez** [comment]
Feito, testem:

http://beta.brasa.art.br/artunlimited/portfolio/agua/

**Comment by diegorojas** [comment]
Isso ta beleza! Agora é sou eu dar uma pensada e fechar um css um pouco mais bacana. Depois dessa parte eu fecho a issue

**Comment by diegorojas** [comment]
@matheusgimenez  por favor troca o "material gráfico" no menu só para "gráfico", e no ingles deixa so "graphic" tb, vai ser foda de deixar bunitinho com esse tamanho de botão..

**Comment by diegorojas** [comment]
Outra coisa de texto para melhorar a usabilidade, agora no front end. No título "Seções", colocar no lugar em português "navegue no conteúdo", e em inglês "browse content"

**Comment by matheusgimenez** [comment]
@diegorojas farei

**Comment by matheusgimenez** [comment]
Feito
