### ISSUE TITLE
Alterar plugin do Clipping

### ISSUE THREAD

**Issue by diogosp** [brasadesign/artunlimited#9]
- Alterar para o Jetpack
- Revisar front-end

**Comment by diegorojas** [comment]
Diogo,

Acho que aqui não há necessidade do uso do JetPack, podemos usar outras coisas no caso, se formo usar o gerenciamento de galerias do Odin para tudo. Certo @matheusgimenez ?

**Comment by diogosp** [comment]
Ótimo @diegorojas  , é que o @matheusgimenez colocou isso na planilha que me enviou.
Por favor alinhem esta solução e me falem como vai ficar.

**Comment by matheusgimenez** [comment]
Foi feito usando galeria padrão do WP.

Talvez precise um tapa melhor no css, colocar aquele efeito de fade com um icone de "+" e talz.

Mas ta no beta, testem:

http://beta.brasa.art.br/artunlimited/portfolio/agua/

**Comment by diegorojas** [comment]
Matt, aqui o desafio era do clique nas imagens irem para o template image.php que está pronto, lembra? Não era tudo que devia abrir no carrousel. o jpeg tem que abrir na largura do site.. e não dentro de um modal.

Elas tem a demanda de ler a matéria inteira de jornal, aqui para relembrar: http://artunlimited.com.br/index.php/portfolio/abraham-palatnik-a-reinvencao-da-luz/palatnik_clipping_01_bx/

**Comment by matheusgimenez** [comment]
Feito

**Comment by diegorojas** [comment]
A navegação na galeria de clipping (image.php) precisa ser alterada. Fica em toda a Biblioteca de Mídia. O jeito mais fácil de resolver e tirando o "Anterior" e o "Proximo" mesmo, deixando somente o "voltar para" e o link para o single post de onde ele veio. Talvez só ancorar na volta para o single, a área de clippings mesmo... será que rola?

**Comment by matheusgimenez** [comment]
Nesse ponto a melhor saida é arrancar fora os botões de navegação mesmo. A alternativa seria de criar um metabox dentro da pagina de edição da imagem (aquela em modal mesmo) e fazer uma função customizada para pegar somente as que tiverem marcadas como clipping. Mas levaria no minimo +2hrs de trampo..

Abraços.

**Comment by matheusgimenez** [comment]
Já arranquei fora os botões, ta no beta. Testa e qlq coisa avisa.

**Comment by diegorojas** [comment]
Perfeito! Já era!
